version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - app:/app
    command: ['nginx-debug', '-g', 'daemon off;']
    links:
      - php
  php:
    build: .
    volumes:
      - .:/var/www
      - app:/app

volumes:
  app:
